import js from "@eslint/js";
import { defineConfig, globalIgnores } from "eslint/config";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";

export default defineConfig([
  // Trailing slashes skip directory traversal outright rather than walking then filtering.
  // `coverage/` is generated by `npm run test:coverage`; flat config does not read .gitignore.
  globalIgnores(["dist/", "src-tauri/", "scripts/", "coverage/"]),

  // Application and test sources.
  {
    files: ["src/**/*.{ts,tsx}", "tests/**/*.{ts,tsx}"],
    // `extends` flattens config arrays, so tseslint.configs.recommended needs no spread.
    extends: [js.configs.recommended, tseslint.configs.recommended],
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  // Root-level build configs, now reachable since `lint` runs `eslint .`.
  {
    files: ["*.config.{js,ts,mts}"],
    extends: [js.configs.recommended, tseslint.configs.recommended],
  },
]);
